[tools]
stack = "3.5.1"

[tasks.build]
description = "Build the app"
run = "stack build"

[tasks.app]
description = "Run the app"
run = "stack run"

[tasks.test]
description = "Run the tests"
run = "type test\\normal.pl0 | stack  run"

[tasks.testWrong]
description = "Run the tests wrong"
run = "type test\\wrong.pl0 | stack  run"