# package.yaml
name: CompilerPrinciples-GUET2022
version: 0.1.0.0
license: MIT
license-file: LICENSE
author: group_of_compile
maintainer: 114514@example.com
extra-doc-files:
  - CHANGELOG.md

dependencies:
  - base >= 4.19.2.0 && < 4.20
  - array >= 0.5 && < 0.6
  - containers >= 0.6.8 && < 0.7.0
  - mtl >= 2.3.1 && < 2.4.0

build-tools:
  - alex >= 3.5.3.0 && < 3.6.0.0
  - happy >= 2.0.2 && < 2.1.0

library:
  source-dirs: lib
  exposed-modules:
    - Lexer
    - Token
    - Ast
    - Parser
    - Compiler
  language: Haskell2010
  ghc-options: -Wall

executables:
  CompilerPrinciples-GUET2022:
    main: Main.hs
    source-dirs: app
    dependencies:
      - CompilerPrinciples-GUET2022
    language: Haskell2010
    ghc-options: -Wall

tests:
  CompilerPrinciples-GUET2022-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - CompilerPrinciples-GUET2022
    language: Haskell2010
    ghc-options: -Wall
